### ISSUE TITLE
Extinction/origination rate calculator

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/data_service#13]
Originally added to pbdb-changelog by @vjpsyverson on 2017-01-24

 Choose and describe algorithms (@vjpsyverson)
 Implement in API (@mmcclenn)
 Make available via downloader (@vjpsyverson)
 (optional) Add to Navigator (@vjpsyverson)

**Comment by vjpsyverson** [comment]
A basic calculator is now implemented in browser. I don't think we need to do more than that.
