### ISSUE TITLE
Ensure that meta-data can be unselected for all API routes

### ISSUE THREAD

**Issue by aazaff** [paleobiodb/data_service#20]
Even if you un-select the include metadata option in the download form, this path still returns the metadata header. Metadata should not be returned for any route if not selected as part of the data form.

https://paleobiodb.org/data1.2/occs/taxa.txt?rank=max_genus&interval=Phanerozoic&limit=100

**Comment by mmcclenn** [comment]
This will be fixed in next week's update. The summary material will only appear in downloads if the "metadata" box is checked (or, equivalently, if the 'datainfo' parameter appears in the download URL). Otherwise, in CSV format, the header line will be the first line of the output.

**Comment by aazaff** [comment]
That's great news, but I was under the impression that you were hesitant to fix this until 1.3 because it could technically be a breaking change for some people?
