### ISSUE TITLE
Changes for navigator 1.2

### ISSUE THREAD

**Issue by mmcclenn** [paleobiodb/data_service#21]
In order to get Navigator using 1.2, the following changes need to be made to the data service:

- [x] fix strata/auto with limit

**Comment by vjpsyverson** [comment]
- [ ] add &count back to colls/list

**Comment by vjpsyverson** [comment]
[] occs/list needs to always report tna (accepted_name)

**Comment by mmcclenn** [comment]
It is not possible for occs/list to always report 'tna', because the taxonomic name to which the occurrence has been identified may not actually be in the taxonomy table. Solution: when 'tna' is not available, use 'idn'.

**Comment by vjpsyverson** [comment]
colls/summary no longer accepts interval_id=0 -- should it? ([example](https://paleobiodb.org/data1.2/colls/summary.json?lngmin=-180&lngmax=180&latmin=-90&latmax=90&limit=all&show=time&level=3&interval_id=0))

**Comment by vjpsyverson** [comment]
strata/auto appears to now ALWAYS set limit=10 and just doesn't accept the parameter anymore. Solution: stop trying to pass it
