### ISSUE TITLE
range through diversity metrics are all problematic

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/data_service#27]
All of the diversity metrics fail to take into account whether or not taxa are exant or not. Even if there are no occurrences in the database, the calculation should assume there are Holocene occurrences if the taxon is marked as Exant. They don't appear to do this.

**Comment by mmcclenn** [comment]
If you include the parameter 'recent', as in "/data1.2/occs/diversity.json?base_name=mammalia&recent" then it is supposed to do this. I haven't actually tested to make sure that works correctly, though. Can you try it and let me know?

**Comment by markuhen** [comment]
I think we are good, and I just made a mistake. Closing for now unless I can demonstrate a real problem. Sorry!
