### ISSUE TITLE
Change permissions for adding type locality in Add/Edit Names

### ISSUE THREAD

**Issue by pnovack-gottshall** [paleobiodb/data_service#35]
The "Type locality (PaleoDB number)" field in the Add/Edit Names page for any taxon seems to be locked so that users can't enter values to the field. It seems to only be entered "internally" when a "n. gen." and/or "n. sp." tag was entered in a biotic list. Because secondary users can't edit other's biotic lists to add the tags, there's really no way for most users to enter values to this field (without annoying the original collection enterer). Can you change the permission to that any user can add the relevant type locality (just as we can add holotype specimen numbers, authority information, etc.).

**Comment by markuhen** [comment]
We are working on changing permissions globally for the DB, hopefully within the next couple of weeks, so stay tuned!

Thanks,

Mark
