### ISSUE TITLE
Large downloads produce 500 error.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/data_service#37]
From Steve Wang (swang1@swarthmore.edu:

I'm trying to download phylum- or class-level datasets from @PaleoDB, but I keep getting '500 Server Error' using either the API or Navigator. It seems to work for smaller taxa (Bryozoa), but not for larger ones (Mollusca). Is there a way to fix this problem, or a workaround?

Example: the following gives me a ‘500 Server error’:

https://paleobiodb.org/data1.2/occs/list.csv?datainfo&rowcount&base_name=MOLLUSCA&taxon_reso=lump_genus&show=class,acconly

but if I replace MOLLUSCA with BRYOZOA, it works fine. It seems to get stuck on larger taxa (with many genera).

I have been able to reproduce this problem.

**Comment by jpjenk** [comment]
Thank you, @mmcclenn. I've tested with the above query and several other large data volume retrievals. Valid data retuned with HTTP Status 200 OK each time. The query mentioned in this thread takes almost 2 minutes to compile so don't worry, it's working.
