### ISSUE TITLE
Recent taxonomic names not in API

### ISSUE THREAD

**Issue by mclapham** [paleobiodb/data_service#47]
It appears that taxonomic names and opinions entered after late March (or thereabouts) aren't output by the API. For example, https://paleobiodb.org/classic/basicTaxonInfo?taxon_no=384026 vs. https://paleobiodb.org/data1.2/taxa/list.txt?id=384026. As best as I can tell, taxonomic names before that one are working fine, but ones after are not included.

**Comment by mmcclenn** [comment]
Restarted nightly build job.
