### ISSUE TITLE
Data service not finding a specific taxon during data retrieval

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/data_service#48]
For some reason, the data service does not find the genus Urkudelphis from the Chattian of Ecuador in collection 190942 when using this query: 

http://paleobiodb.org/data1.2/occs/taxa.csv?datainfo&rowcount&base_name=Cetacea&rank=genus&taxon_status=accepted&interval=Chattian&cc=SOA&private&show=full

And it should.

**Comment by mmcclenn** [comment]
I found the bug, and fixed it. The output now includes Urkudelphis, as it should.
