### ISSUE TITLE
Is a DarwinCore Archive file available somewhere?

### ISSUE THREAD

**Issue by dimus** [paleobiodb/data_service#50]
Would be great to have a DarwinCore rendering of the data. Hopefully it already exists somewhere?

**Comment by mmcclenn** [comment]
We do have dataset included in GBIF, which is in Darwin Core format. Unfortunately, it hasn't been updated since 2017. At some point, we should really do something about that. But for the time being, you can find download dataset at https://www.gbif.org/dataset/bb5b30b4-827e-4d5e-a86a-825d65cb6583.

**Comment by dimus** [comment]
Thanks! And yes, would be great to have a fresh DwCA!
