### ISSUE TITLE
Internal server error when specifying filtering parameters in occs/refs

### ISSUE THREAD

**Issue by castroinsua** [paleobiodb/data_service#61]
Many of the parameters that are used to filter the result set in the `occs/refs` endpoint produce an internal server error. For example, the following request returns around 800 records:

https://paleobiodb.org/data1.2/occs/refs.json?base_name=Cetacea&interval=Miocene

But trying to filter by year produces a response with `"status_code": 500`

https://paleobiodb.org/data1.2/occs/refs.json?base_name=Cetacea&interval=Miocene&ref_pubyr=2005

This also seems to happen with other parameters such as `ref_author`, `ref_title`, or `pub_type`. However, `ref_id` works fine:

https://paleobiodb.org/data1.2/occs/refs.json?base_name=Cetacea&interval=Miocene&ref_id=12988

**Comment by mmcclenn** [comment]
Thank you for bringing this to my attention! I have fixed this bug. The reference filter parameters now work properly with the following operations:

- occs/refs
- occs/byref
- occs/taxabyref
- occs/opinions

**Comment by castroinsua** [comment]
Thank you very much for fixing it!
